# -----------------------------------------------------------
#
#
#  PHP CONFIG TO OVERRIDE DEV CONFIG
#  for base config check the .dist file
#
#
# -----------------------------------------------------------


#display_errors = Off
#date.timezone = UTC
memory_limit = 4096M
max_execution_time = 350

[mail function]
SMTP = mailhog
smtp_port = 1025
sendmail_path = null
mail.add_x_header = On
mail.log = /var/log/phpMail.log
;sendmail_path =  /usr/sbin/sendmail -S mailhog:1025 -t

display_errors = Off
