#!/bin/sh
set -e

# This script working dir is application's directory, and all ENV variables from .env and OS are available here
# using ${ENV_NAME} with defaults taken from .env and .env.<env>

# Put Custom Ad-hoc scripts below:

## Run Envsubst on .env to expand embedded Env Variables
echo "► Expanding Dotenv files with Environment Variables..."
for f in $(find . -name ".env*"); do cat $f | envsubst "$(env | sed -e 's/=.*//' -e 's/^/\$/g')" > "$f.tmp"; mv "$f.tmp" "$f"; done
